debug: True
seed: 42
## Loging options
logging:
  exp_name: 'exp1'
  base_dir: './logs'

## Data parameters
data:
  name: 'MNIST'
  dataset_parameters:
    validation_size: 5000
    normalize: True
    flip: False
    crop: True
    num_workers: 2
    batch_size: 64
    test_batch_size: 100

## Model parameters
model:
  model_name: 'LeNet'
  model_parameters:
    n_classes: 10

# Optimization parameters
optimization:
  n_epochs: 30
  optimizer: adam
  lr: 0.001
  weight_decay: 0.

